import = [
  "~/.config/alacritty/themes/light.toml"
]

[font]
size = 12.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[window]
decorations = "buttonless"
dynamic_padding = true
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 200
lines = 60

[window.padding]
x = 0
y = 0

[env]
TERM = "xterm-256color"

