#!/usr/bin/env zsh

STOW_FOLDERS="zsh,nvim,git,curl,brew,starship,ghostty,helix,zellij"

stow -t ~ stow

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Stowing $folder"
    stow --restow -vvv $folder
done

echo "Done."
