#!/usr/bin/env zsh

STOW_FOLDERS="zsh,git,curl,brew,starship,ghostty,helix,zellij,swiftformat,opencode,bat,delta,launchd,agents,direnv"

stow -t ~ stow

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Stowing $folder"
    stow --restow -vvv $folder
done

echo "Done."
