#!/usr/bin/env fish

rm -f ~/.zcompdump
chmod -R go-w "$(brew --prefix)/share"

echo "Brewing..."
brew bundle --no-lock --file ~/.Brewfile --quiet --zap

eval (brew --prefix)/opt/fzf/install \
  --no-zsh \
  --no-bash \
  --key-bindings \
  --completion \
  --no-update-rc

# Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -q -y --no-modify-path
